<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="System.IO" />
    <Using Include="System.Text.RegularExpressions" />
    <Using Include="System.Xml.Linq" />
    <Using Include="Microsoft.Extensions.Logging.Abstractions" />
    <Using Include="__Product__.App.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\__Product__.App\__Product__.App.csproj" />
  </ItemGroup>
</Project>
