#:property PublishAot=false
// Adds outline icons (Fluent UI System Icons, 24px Regular, MIT) to a project and regenerates Icons.g.cs.
// Run through add-icons.bat. Args: <ProjectRoot> [icon_name ...]   e.g. add-icons.bat C:\Projects\MyApp person_add filter
// Names are snake_case as on https://github.com/microsoft/fluentui-system-icons (folder "Person Add" -> person_add).
using System.Text;
using System.Text.RegularExpressions;

const string Source = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets";

try
{
    if (args.Length < 1) return Fail("Usage: add-icons.bat <ProjectRoot> [icon_name ...]");
    var appDir = Directory.GetDirectories(Path.Combine(Path.GetFullPath(args[0]), "src"), "*.App").SingleOrDefault()
        ?? throw new InvalidOperationException("No src\\*.App project found under the project root.");
    var appNamespace = Path.GetFileName(appDir);
    var listFile = Path.Combine(appDir, "Resources", "icons.txt");

    var names = (File.Exists(listFile) ? File.ReadAllLines(listFile) : [])
        .Concat(args.Skip(1))
        .Select(n => n.Trim().ToLowerInvariant())
        .Where(n => n.Length > 0)
        .Distinct()
        .Order(StringComparer.Ordinal)
        .ToList();
    if (names.Count == 0) return Fail("No icon names given.");

    using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
    var icons = new List<(string Kind, string Data)>();
    foreach (var name in names)
    {
        if (!Regex.IsMatch(name, "^[a-z0-9_]+$")) return Fail($"Invalid icon name '{name}'. Use snake_case, e.g. person_add.");
        icons.Add((ToPascal(name), await Fetch(http, name)));
    }

    File.WriteAllLines(listFile, names);
    File.WriteAllText(Path.Combine(appDir, "Resources", "Icons.g.cs"), Render(appNamespace, icons), new UTF8Encoding(false));
    Console.WriteLine($"[add-icons] OK: {icons.Count} icons in {appNamespace}\\Resources\\Icons.g.cs");
    return 0;
}
catch (Exception ex)
{
    return Fail(ex.Message);
}

static int Fail(string message)
{
    Console.Error.WriteLine($"[add-icons] FAILED: {message}");
    return 1;
}

static string ToPascal(string snake) =>
    string.Concat(snake.Split('_').Select(w => char.ToUpperInvariant(w[0]) + w[1..]));

static async Task<string> Fetch(HttpClient http, string name)
{
    // Folder names are Title Case; a few use upper-case acronyms (LTR, RTL).
    var words = name.Split('_');
    string[] folders =
    [
        string.Join(' ', words.Select(w => char.ToUpperInvariant(w[0]) + w[1..])),
        string.Join(' ', words.Select(w => w is "ltr" or "rtl" ? w.ToUpperInvariant() : char.ToUpperInvariant(w[0]) + w[1..])),
    ];
    foreach (var folder in folders.Distinct())
    {
        var url = $"{Source}/{Uri.EscapeDataString(folder)}/SVG/ic_fluent_{name}_24_regular.svg";
        using var response = await http.GetAsync(url);
        if (!response.IsSuccessStatusCode) continue;
        var svg = await response.Content.ReadAsStringAsync();
        var paths = Regex.Matches(svg, "<path[^>]*?\\sd=\"(?<d>[^\"]+)\"[^>]*>");
        if (paths.Count == 0) throw new InvalidOperationException($"'{name}' has no path data.");
        var evenOdd = svg.Contains("evenodd", StringComparison.Ordinal);
        return (evenOdd ? "F0 " : "F1 ") + string.Join(' ', paths.Select(p => p.Groups["d"].Value));
    }
    throw new InvalidOperationException($"Icon '{name}' not found. Check the name on github.com/microsoft/fluentui-system-icons.");
}

static string Render(string ns, List<(string Kind, string Data)> icons)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated> by scripts/add-icons from Resources/icons.txt. Do not edit by hand.");
    sb.AppendLine("// Fluent UI System Icons, 24px Regular (outline). MIT License, Copyright (c) Microsoft Corporation.");
    sb.AppendLine($"namespace {ns}.Resources;");
    sb.AppendLine();
    sb.AppendLine("public enum IconKind");
    sb.AppendLine("{");
    foreach (var icon in icons) sb.AppendLine($"    {icon.Kind},");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("public static class IconData");
    sb.AppendLine("{");
    sb.AppendLine("    public static string Get(IconKind kind) => kind switch");
    sb.AppendLine("    {");
    foreach (var icon in icons) sb.AppendLine($"        IconKind.{icon.Kind} => \"{icon.Data}\",");
    sb.AppendLine("        _ => string.Empty,");
    sb.AppendLine("    };");
    sb.AppendLine("}");
    return sb.ToString().ReplaceLineEndings("\r\n");
}
